name: Docker Image CI

on:
  push:
    paths-ignore: 
      - "README.md"
    branches:
    - master
  schedule:
    - cron:  "0 0 * * 0"
  pull_request:
    paths-ignore: 
      - "README.md"
    branches:
    - master
      

jobs:
  
  trivy:
     name: Scan for Vuls 
     runs-on: ubuntu-latest
     strategy:
      fail-fast: false
      matrix:
        tags: [latest, node-10, node-12, node-14]
     steps:
        - name: Login to DockerHub Registry
          run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        - name: Pull docker image
          run: docker pull ${{secrets.DOCKER_USERNAME }}/pimatic:${{ matrix.tags }}
        - name: Trivy Action
          uses: homoluctus/gitrivy@v2
          with:
            image: ${{secrets.DOCKER_USERNAME }}/pimatic:${{ matrix.tags }}
            token: ${{ secrets.GITHUB_TOKEN }}
            issue: false

  snyk:
    name: Snyk - Security Check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:        
        tag: [latest, node-10, node-12, node-14]
    steps:
        - uses: actions/checkout@master
        - name: Run Snyk to check for vulnerabilities
          uses: snyk/actions/docker@master
          env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          with:
            image: ${{secrets.DOCKER_USERNAME }}/pimatic:${{matrix.tag}}
            args: --severity-threshold=high
